name: Process Data

on:
  push:
    branches:
      - main

jobs:
  run_script:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prompt user for input value
      run: echo ::set-output name=input_value::$(read -p "Enter the input value: " val && echo $$val)

    - name: Run script
      run: python main.py ${{ steps.prompt.outputs.input_value }}
