name: Process Data

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install openpyxl
      - name: Run script
        run: |
          echo $(cat input_data.xlsx | base64 -w 0) | base64 -d > input_data_decoded.xlsx
          echo $(python main.py < input_data_decoded.xlsx)
