name: Process Data

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install openpyxl
    - name: Run script
      run: python main.py A1
